-- Account overhaul: profile expansion + buyer/seller feature tables.
-- Additive-only. Uses the Phase 1 baseline (public.is_admin, tg_touch_updated_at).
-- Safe to re-run: every CREATE is idempotent and every policy is DROP-IF-EXISTS
-- before being re-created deterministically.

begin;

-- ============================================================================
-- 1) profiles: extend with marketplace-grade columns. All are nullable/default
--    so the column adds are non-breaking for existing rows. JSONB payloads
--    keep this iteration light; they can be normalized into relational tables
--    in a later phase without touching UI wiring.
-- ============================================================================

alter table public.profiles
  add column if not exists bio               text,
  add column if not exists website_url       text,
  add column if not exists entity_type       text,
  add column if not exists company_name      text,
  add column if not exists tax_id            text,
  add column if not exists reg_com           text,
  add column if not exists vat_id            text,
  add column if not exists fiscal_address    jsonb,
  add column if not exists seller_activated_at timestamptz,
  add column if not exists preferences       jsonb not null default '{}'::jsonb,
  add column if not exists seller_policies   jsonb not null default '{}'::jsonb,
  add column if not exists supplier_settings jsonb not null default '{}'::jsonb;

do $$
begin
  alter table public.profiles
    drop constraint if exists profiles_entity_type_check;
exception when others then null;
end $$;

alter table public.profiles
  add constraint profiles_entity_type_check
  check (entity_type is null or entity_type in ('PF','PFA','SRL','SA','II','IF'));

-- Open SELECT on the new public-safe columns so the public_profiles view
-- plus joins (e.g. a seller detail page) can read them without leaking
-- phone/role. Sensitive columns (tax_id, reg_com, vat_id, fiscal_address)
-- stay off this grant — only self-or-admin policy can read them.
grant select (
  id, display_name, avatar_path, bio, website_url, company_name,
  entity_type, seller_activated_at
) on public.profiles to anon, authenticated;

-- ============================================================================
-- 2) user_addresses: one user → many addresses. Flags mark defaults; partial
--    unique indexes enforce at most one default-billing and one default-shipping.
-- ============================================================================

create table if not exists public.user_addresses (
  id                     bigint generated by default as identity primary key,
  user_id                uuid not null references auth.users(id) on delete cascade,
  label                  text,
  recipient              text,
  line1                  text not null,
  line2                  text,
  city                   text not null,
  county                 text,
  postal_code            text,
  country                text not null default 'RO',
  phone                  text,
  notes                  text,
  is_default_billing     boolean not null default false,
  is_default_shipping    boolean not null default false,
  pickup_lat             numeric,
  pickup_lng             numeric,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint user_addresses_line1_nonempty   check (char_length(line1) between 1 and 200),
  constraint user_addresses_city_nonempty    check (char_length(city)  between 1 and 120),
  constraint user_addresses_lat_range        check (pickup_lat is null or (pickup_lat between -90  and 90)),
  constraint user_addresses_lng_range        check (pickup_lng is null or (pickup_lng between -180 and 180))
);

create index if not exists user_addresses_user_id_idx
  on public.user_addresses (user_id);

create unique index if not exists user_addresses_one_default_billing_idx
  on public.user_addresses (user_id)
  where is_default_billing;

create unique index if not exists user_addresses_one_default_shipping_idx
  on public.user_addresses (user_id)
  where is_default_shipping;

drop trigger if exists touch_updated_at on public.user_addresses;
create trigger touch_updated_at
  before update on public.user_addresses
  for each row execute function public.tg_touch_updated_at();

alter table public.user_addresses enable row level security;
do $$ begin execute 'alter table public.user_addresses force row level security'; exception when others then null; end $$;

drop policy if exists "user_addresses_select_self" on public.user_addresses;
drop policy if exists "user_addresses_insert_self" on public.user_addresses;
drop policy if exists "user_addresses_update_self" on public.user_addresses;
drop policy if exists "user_addresses_delete_self" on public.user_addresses;

create policy "user_addresses_select_self"
on public.user_addresses for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "user_addresses_insert_self"
on public.user_addresses for insert
to authenticated
with check (auth.uid() = user_id);

create policy "user_addresses_update_self"
on public.user_addresses for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "user_addresses_delete_self"
on public.user_addresses for delete
to authenticated
using (auth.uid() = user_id);

-- user_id lock: belt-and-suspenders so an update cannot reassign rows.
create or replace function public.tg_user_addresses_lock_user_id()
returns trigger
language plpgsql
as $$
begin
  if new.user_id is distinct from old.user_id then
    raise exception 'user_id is immutable' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists user_addresses_lock_user_id on public.user_addresses;
create trigger user_addresses_lock_user_id
  before update on public.user_addresses
  for each row execute function public.tg_user_addresses_lock_user_id();

-- ============================================================================
-- 3) user_notification_preferences: single row per user; PK = user_id.
-- ============================================================================

create table if not exists public.user_notification_preferences (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  channels     jsonb not null default '{"email":true,"sms":false,"push":false}'::jsonb,
  topics       jsonb not null default '{"orders":true,"bids":true,"messages":true,"marketing":false,"security":true}'::jsonb,
  quiet_hours  jsonb,
  updated_at   timestamptz not null default now()
);

drop trigger if exists touch_updated_at on public.user_notification_preferences;
create trigger touch_updated_at
  before update on public.user_notification_preferences
  for each row execute function public.tg_touch_updated_at();

alter table public.user_notification_preferences enable row level security;
do $$ begin execute 'alter table public.user_notification_preferences force row level security'; exception when others then null; end $$;

drop policy if exists "user_notif_select_self" on public.user_notification_preferences;
drop policy if exists "user_notif_upsert_self" on public.user_notification_preferences;
drop policy if exists "user_notif_update_self" on public.user_notification_preferences;
drop policy if exists "user_notif_delete_self" on public.user_notification_preferences;

create policy "user_notif_select_self"
on public.user_notification_preferences for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "user_notif_upsert_self"
on public.user_notification_preferences for insert
to authenticated
with check (auth.uid() = user_id);

create policy "user_notif_update_self"
on public.user_notification_preferences for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "user_notif_delete_self"
on public.user_notification_preferences for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================================
-- 4) wishlist_items: saved marketplace listings only (one row per user+listing).
-- ============================================================================

create table if not exists public.wishlist_items (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  listing_id  bigint not null references public.marketplace_listings(id) on delete cascade,
  added_at    timestamptz not null default now(),
  constraint wishlist_items_user_listing_uniq unique (user_id, listing_id)
);

create index if not exists wishlist_items_user_id_idx on public.wishlist_items (user_id);
create index if not exists wishlist_items_listing_id_idx on public.wishlist_items (listing_id);

alter table public.wishlist_items enable row level security;
do $$ begin execute 'alter table public.wishlist_items force row level security'; exception when others then null; end $$;

drop policy if exists "wishlist_items_select_self" on public.wishlist_items;
drop policy if exists "wishlist_items_insert_self" on public.wishlist_items;
drop policy if exists "wishlist_items_delete_self" on public.wishlist_items;

create policy "wishlist_items_select_self"
on public.wishlist_items for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "wishlist_items_insert_self"
on public.wishlist_items for insert
to authenticated
with check (auth.uid() = user_id);

-- No UPDATE policy: wishlist rows are immutable once written.
create policy "wishlist_items_delete_self"
on public.wishlist_items for delete
to authenticated
using (auth.uid() = user_id);

revoke update on public.wishlist_items from anon, authenticated;

-- ============================================================================
-- 5) reviews: buyer → seller, optionally bound to an order/listing.
--    Anyone can SELECT (public reputation); only reviewer can modify own row;
--    target_user_id cannot touch rows targeting them.
-- ============================================================================

create table if not exists public.reviews (
  id               bigint generated by default as identity primary key,
  reviewer_id      uuid not null references auth.users(id) on delete cascade,
  target_user_id   uuid not null references auth.users(id) on delete cascade,
  order_id         bigint,
  listing_id       bigint references public.marketplace_listings(id) on delete set null,
  rating           integer not null,
  title            text,
  body             text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint reviews_rating_range        check (rating between 1 and 5),
  constraint reviews_body_len            check (body is null or char_length(body) between 1 and 4000),
  constraint reviews_title_len           check (title is null or char_length(title) between 1 and 200),
  constraint reviews_reviewer_ne_target  check (reviewer_id <> target_user_id)
);

-- One review per reviewer per listing subject. Order-based uniqueness once orders land.
create unique index if not exists reviews_reviewer_listing_uniq
  on public.reviews (reviewer_id, listing_id)
  where listing_id is not null;

create index if not exists reviews_target_user_id_idx  on public.reviews (target_user_id);
create index if not exists reviews_reviewer_id_idx     on public.reviews (reviewer_id);
create index if not exists reviews_listing_id_idx      on public.reviews (listing_id);
create index if not exists reviews_created_at_idx      on public.reviews (created_at desc);

drop trigger if exists touch_updated_at on public.reviews;
create trigger touch_updated_at
  before update on public.reviews
  for each row execute function public.tg_touch_updated_at();

alter table public.reviews enable row level security;
do $$ begin execute 'alter table public.reviews force row level security'; exception when others then null; end $$;

drop policy if exists "reviews_select_public"     on public.reviews;
drop policy if exists "reviews_insert_reviewer"   on public.reviews;
drop policy if exists "reviews_update_reviewer"   on public.reviews;
drop policy if exists "reviews_delete_reviewer"   on public.reviews;

create policy "reviews_select_public"
on public.reviews for select
to anon, authenticated
using (true);

create policy "reviews_insert_reviewer"
on public.reviews for insert
to authenticated
with check (auth.uid() = reviewer_id);

create policy "reviews_update_reviewer"
on public.reviews for update
to authenticated
using (auth.uid() = reviewer_id or public.is_admin())
with check (auth.uid() = reviewer_id or public.is_admin());

create policy "reviews_delete_reviewer"
on public.reviews for delete
to authenticated
using (auth.uid() = reviewer_id or public.is_admin());

-- Lock reviewer/target ids on update.
create or replace function public.tg_reviews_lock_ids()
returns trigger
language plpgsql
as $$
begin
  if new.reviewer_id is distinct from old.reviewer_id then
    raise exception 'reviewer_id is immutable' using errcode = '42501';
  end if;
  if new.target_user_id is distinct from old.target_user_id then
    raise exception 'target_user_id is immutable' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists reviews_lock_ids on public.reviews;
create trigger reviews_lock_ids
  before update on public.reviews
  for each row execute function public.tg_reviews_lock_ids();

-- ============================================================================
-- 6) message_threads + messages: minimal 1-to-1 inbox scoped by context.
-- ============================================================================

create table if not exists public.message_threads (
  id                bigint generated by default as identity primary key,
  buyer_id          uuid not null references auth.users(id) on delete cascade,
  seller_id         uuid not null references auth.users(id) on delete cascade,
  subject           text,
  context_type      text,
  context_id        bigint,
  last_message_at   timestamptz not null default now(),
  created_at        timestamptz not null default now(),
  constraint message_threads_buyer_ne_seller   check (buyer_id <> seller_id),
  constraint message_threads_context_enum      check (context_type is null or context_type in ('order','listing'))
);

create unique index if not exists message_threads_unique_ctx_idx
  on public.message_threads (buyer_id, seller_id, context_type, context_id)
  where context_type is not null and context_id is not null;

create index if not exists message_threads_buyer_idx    on public.message_threads (buyer_id);
create index if not exists message_threads_seller_idx   on public.message_threads (seller_id);
create index if not exists message_threads_last_msg_idx on public.message_threads (last_message_at desc);

alter table public.message_threads enable row level security;
do $$ begin execute 'alter table public.message_threads force row level security'; exception when others then null; end $$;

drop policy if exists "threads_select_member" on public.message_threads;
drop policy if exists "threads_insert_member" on public.message_threads;
drop policy if exists "threads_update_member" on public.message_threads;
drop policy if exists "threads_no_delete"     on public.message_threads;

create policy "threads_select_member"
on public.message_threads for select
to authenticated
using (auth.uid() in (buyer_id, seller_id) or public.is_admin());

create policy "threads_insert_member"
on public.message_threads for insert
to authenticated
with check (auth.uid() in (buyer_id, seller_id));

-- last_message_at touch-ups are allowed for members (done by trigger below too).
create policy "threads_update_member"
on public.message_threads for update
to authenticated
using (auth.uid() in (buyer_id, seller_id) or public.is_admin())
with check (auth.uid() in (buyer_id, seller_id) or public.is_admin());

create policy "threads_no_delete"
on public.message_threads for delete
to authenticated
using (public.is_admin());

create table if not exists public.messages (
  id            bigint generated by default as identity primary key,
  thread_id     bigint not null references public.message_threads(id) on delete cascade,
  sender_id     uuid not null references auth.users(id) on delete cascade,
  body          text not null,
  attachments   jsonb not null default '[]'::jsonb,
  read_at       timestamptz,
  created_at    timestamptz not null default now(),
  constraint messages_body_len check (char_length(body) between 1 and 4000)
);

create index if not exists messages_thread_id_idx  on public.messages (thread_id, created_at);
create index if not exists messages_sender_id_idx  on public.messages (sender_id);

alter table public.messages enable row level security;
do $$ begin execute 'alter table public.messages force row level security'; exception when others then null; end $$;

drop policy if exists "messages_select_member"  on public.messages;
drop policy if exists "messages_insert_member"  on public.messages;
drop policy if exists "messages_update_member"  on public.messages;
drop policy if exists "messages_no_delete"      on public.messages;

create policy "messages_select_member"
on public.messages for select
to authenticated
using (
  exists (
    select 1 from public.message_threads mt
    where mt.id = messages.thread_id
      and (auth.uid() in (mt.buyer_id, mt.seller_id) or public.is_admin())
  )
);

create policy "messages_insert_member"
on public.messages for insert
to authenticated
with check (
  auth.uid() = sender_id
  and exists (
    select 1 from public.message_threads mt
    where mt.id = thread_id
      and auth.uid() in (mt.buyer_id, mt.seller_id)
  )
);

-- Only the recipient can mark read_at; sender cannot modify the body.
create policy "messages_update_member"
on public.messages for update
to authenticated
using (
  exists (
    select 1 from public.message_threads mt
    where mt.id = messages.thread_id
      and auth.uid() in (mt.buyer_id, mt.seller_id)
  )
)
with check (
  exists (
    select 1 from public.message_threads mt
    where mt.id = messages.thread_id
      and auth.uid() in (mt.buyer_id, mt.seller_id)
  )
);

create policy "messages_no_delete"
on public.messages for delete
to authenticated
using (public.is_admin());

-- Freeze body/sender/thread against tampering via PostgREST.
create or replace function public.tg_messages_lock_body()
returns trigger
language plpgsql
as $$
begin
  if new.thread_id is distinct from old.thread_id then
    raise exception 'thread_id is immutable' using errcode = '42501';
  end if;
  if new.sender_id is distinct from old.sender_id then
    raise exception 'sender_id is immutable' using errcode = '42501';
  end if;
  if new.body is distinct from old.body then
    raise exception 'body is immutable' using errcode = '42501';
  end if;
  if new.attachments is distinct from old.attachments then
    raise exception 'attachments are immutable' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists messages_lock_body on public.messages;
create trigger messages_lock_body
  before update on public.messages
  for each row execute function public.tg_messages_lock_body();

-- Bump thread.last_message_at on every INSERT into messages.
create or replace function public.tg_messages_touch_thread()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.message_threads
     set last_message_at = new.created_at
   where id = new.thread_id;
  return new;
end;
$$;

drop trigger if exists messages_touch_thread on public.messages;
create trigger messages_touch_thread
  after insert on public.messages
  for each row execute function public.tg_messages_touch_thread();

-- ============================================================================
-- 7) login_events: audit trail surfaced in Security tab. Self-read only.
-- ============================================================================

create table if not exists public.login_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  ip          inet,
  user_agent  text,
  event       text not null,
  created_at  timestamptz not null default now(),
  constraint login_events_event_enum
    check (event in ('login','logout','password_change','session_revoked'))
);

create index if not exists login_events_user_id_created_idx
  on public.login_events (user_id, created_at desc);

alter table public.login_events enable row level security;
do $$ begin execute 'alter table public.login_events force row level security'; exception when others then null; end $$;

drop policy if exists "login_events_select_self" on public.login_events;
drop policy if exists "login_events_insert_self" on public.login_events;
drop policy if exists "login_events_no_mutate"   on public.login_events;

create policy "login_events_select_self"
on public.login_events for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "login_events_insert_self"
on public.login_events for insert
to authenticated
with check (auth.uid() = user_id);

create policy "login_events_no_mutate"
on public.login_events for update
to authenticated
using (false)
with check (false);

revoke update, delete on public.login_events from anon, authenticated;

-- ============================================================================
-- 8) account_deletion_requests: soft-delete queue (14-day window).
-- ============================================================================

create table if not exists public.account_deletion_requests (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null unique references auth.users(id) on delete cascade,
  requested_at   timestamptz not null default now(),
  scheduled_for  timestamptz not null,
  reason         text,
  status         text not null default 'pending',
  constraint account_deletion_requests_status_enum
    check (status in ('pending','processing','completed','cancelled'))
);

create index if not exists account_deletion_requests_status_idx
  on public.account_deletion_requests (status, scheduled_for);

alter table public.account_deletion_requests enable row level security;
do $$ begin execute 'alter table public.account_deletion_requests force row level security'; exception when others then null; end $$;

drop policy if exists "del_req_select_self"  on public.account_deletion_requests;
drop policy if exists "del_req_insert_self"  on public.account_deletion_requests;
drop policy if exists "del_req_update_self"  on public.account_deletion_requests;
drop policy if exists "del_req_delete_admin" on public.account_deletion_requests;

create policy "del_req_select_self"
on public.account_deletion_requests for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "del_req_insert_self"
on public.account_deletion_requests for insert
to authenticated
with check (auth.uid() = user_id and status = 'pending');

-- Self can only transition pending → cancelled. Admin handles processing/completed.
create policy "del_req_update_self"
on public.account_deletion_requests for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (
  public.is_admin()
  or (auth.uid() = user_id and status in ('pending','cancelled'))
);

create policy "del_req_delete_admin"
on public.account_deletion_requests for delete
to authenticated
using (public.is_admin());

-- ============================================================================
-- 9) Comments for maintainers
-- ============================================================================

comment on table public.user_addresses is
  'Per-user address book. Partial unique indexes enforce at most one default billing/shipping row.';

comment on table public.wishlist_items is
  'Saved marketplace listings per user (unique user_id + listing_id).';

comment on table public.reviews is
  'Marketplace reputation. Public-read so seller pages can show rating distribution; reviewer-only write.';

comment on table public.message_threads is
  'Buyer-seller inbox thread. Context type/id binds the thread to an order or listing.';

comment on table public.account_deletion_requests is
  'Soft-delete queue. User creates a pending row; admin RPC completes the deletion after scheduled_for.';

commit;
